#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

# Parse arguments for library compilation
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments

# 1) Build the library in multiphaseSystems
wmake libso multiphaseSystems || exit 1

# 2) Build the main target in the current directory (solver/utility)
wmake $targetType || exit 1

exit 0
#------------------------------------------------------------------------------
