#!/bin/sh
cd ${0%/*} || exit 1    
. "$WM_PROJECT_DIR"/wmake/scripts/AllwmakeParseArguments
#------------------------------------------------------------------------------

if [ "$BUILD_WITH_ULF" == "true" ]; then
  wmake -all $targetType interpolateData
fi

#------------------------------------------------------------------------------
